"""
Django settings for jiamo project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*4$oz)yu5u3nix6p6bfg^0+_6j4@ii0r%7@p^2$lzqcoic!%xt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jiamo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jiamo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


LOCATIONS = {
    "1": {
        "name": "竹园1号楼",
        "location": [108.840477, 34.126696]
    },
    "2": {
        "name": "竹园2号楼",
        "location": [108.840477, 34.126696]
    },
    "3": {
        "name": "竹园3号楼",
        "location": [108.838792, 34.127424]
    },
    "4": {
        "name": "竹园4号楼",
        "location": [108.838792, 34.127424]
    },
    "5": {
        "name": "海棠5号楼",
        "location": [108.835348, 34.128974]
    },
    "6": {
        "name": "海棠6号楼",
        "location": [108.834501, 34.129329]
    },
    "7": {
        "name": "海棠7号楼",
        "location": [108.832757, 34.130035]
    },
    "8": {
        "name": "海棠8号楼",
        "location": [108.832757, 34.130035]
    },
    "9": {
        "name": "海棠9号楼",
        "location": [108.832087, 34.128969]
    },
    "10": {
        "name": "海棠10号楼",
        "location": [108.832087, 34.128969]
    },

    "11": {
        "name": "丁香11号楼",
        "location": [108.832087, 34.128969]
    },

    "12": {
        "name": "丁香12号楼",
        "location": [108.828321, 34.122952]
    },

    "13": {
        "name": "丁香13号楼",
        "location": [108.828321, 34.122952]
    },
    "14": {
        "name": "丁香14号楼",
        "location": [108.830225, 34.12214]
    },

    "15": {
        "name": "丁香15号楼",
        "location": [108.830225, 34.12214]
    },
}
